{% set version = "0.4.1" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-downloadthis
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/downloadthis_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/downloadthis/downloadthis_{{ version }}.tar.gz
  sha256: a9071a6513469d764028a493b188308806f039c9b76c1fd336b410e9d3620b26

build:
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-b64
    - r-bsplus
    - r-fs
    - r-ggplot2
    - r-htmltools
    - r-magrittr
    - r-mime
    - r-readr
    - r-writexl
    - r-zip
  run:
    - r-base
    - r-b64
    - r-bsplus
    - r-fs
    - r-ggplot2
    - r-htmltools
    - r-magrittr
    - r-mime
    - r-readr
    - r-writexl
    - r-zip

test:
  commands:
    - $R -e "library('downloadthis')"           # [not win]
    - "\"%R%\" -e \"library('downloadthis')\""  # [win]

about:
  home: https://github.com/fmmattioni/downloadthis
  license: MIT
  summary: Implement download buttons in HTML output from 'rmarkdown' without the need for 'runtime:shiny'.
  license_family: MIT
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/MIT'
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
