{% set version = '0.3.2' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-downloadthis
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/downloadthis_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/downloadthis/downloadthis_{{ version }}.tar.gz
  sha256: 678bee329dcb3c761d3375efb31f6f216472bc6d369ac88f01221a808c853988

build:
  merge_build_host: True  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-base64enc
    - r-bsplus
    - r-fs
    - r-ggplot2
    - r-htmltools
    - r-magrittr
    - r-mime
    - r-readr
    - r-writexl
    - r-zip
  run:
    - r-base
    - r-base64enc
    - r-bsplus
    - r-fs
    - r-ggplot2
    - r-htmltools
    - r-magrittr
    - r-mime
    - r-readr
    - r-writexl
    - r-zip

test:
  commands:
    - $R -e "library('downloadthis')"           # [not win]
    - "\"%R%\" -e \"library('downloadthis')\""  # [win]

about:
  home: https://github.com/fmmattioni/downloadthis
  license: MIT
  summary: Implement download buttons in HTML output from 'rmarkdown' without the need for 'runtime:shiny'.
  license_family: MIT
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/MIT'
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: downloadthis
# Title: Implement Download Buttons in 'rmarkdown'
# Version: 0.3.2
# Authors@R: c( person(given = "Felipe", family = "Mattioni Maturana", role = c("aut", "cre"), email = "felipe.mattioni@med.uni-tuebingen.de", comment = c(ORCID = "0000-0002-4221-6104")), person(given = "John", family = "Coene", role = c("ctb"), email = "jcoenep@gmail.com") )
# Description: Implement download buttons in HTML output from 'rmarkdown' without the need for 'runtime:shiny'.
# License: MIT + file LICENSE
# URL: https://github.com/fmmattioni/downloadthis
# BugReports: https://github.com/fmmattioni/downloadthis/issues
# Encoding: UTF-8
# Imports: fs, readr, writexl, bsplus, mime, htmltools, magrittr, zip, ggplot2, base64enc
# RoxygenNote: 7.2.1
# Suggests: knitr, rmarkdown, testthat (>= 3.0.1), spelling, covr
# VignetteBuilder: knitr
# Language: en-US
# Config/testthat/edition: 3
# Config/testthat/parallel: true
# NeedsCompilation: no
# Packaged: 2022-08-16 07:11:22 UTC; fmattioni
# Author: Felipe Mattioni Maturana [aut, cre] (<https://orcid.org/0000-0002-4221-6104>), John Coene [ctb]
# Maintainer: Felipe Mattioni Maturana <felipe.mattioni@med.uni-tuebingen.de>
# Repository: CRAN
# Date/Publication: 2022-08-16 14:10:06 UTC
